[package]
name = "denpk2"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
flate2 = "1.0.30"
libc = "0.2.155"
lz4_flex = "0.11.3"
once_cell = "1.19.0"
openssl = "0.10.64"
# decompyle_rs = { path = "../decompyle_rs" }
